# Generated by Django 4.0.1 on 2022-02-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easy_votings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'курьер', 'verbose_name_plural': 'курьеры'},
        ),
    ]
